apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: concourse
  name: concourse
spec:
  storageClassName: concourse-pv
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: name
              operator: In
              values:
                - minikube
  hostPath:
    path: /data/concourse/
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: concourse
  name: concourse-pv
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: 'true'
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: k8s.io/minikube-hostpath
